# POSTTEST 4
## DATA PREPROCESSING

## IMPORT PACKAGE
- Pandas
- Numpy
- Scikit-learn

In [1]:
import pandas as pd
import numpy as np

# Data Split
# Testing dan Training data
from sklearn.model_selection import train_test_split 

# Data Transforming
# Standarisasi
from sklearn.preprocessing import StandardScaler 

# Normalisasi
from sklearn.preprocessing import MinMaxScaler

# Data Cleaning
# Subtitusi nilai
from sklearn.impute import SimpleImputer 

# Data Encoding
# Onehot
from sklearn.preprocessing import OneHotEncoder

File CSV

In [2]:
dataset_pes = pd.read_csv('deets-updated.csv')
dataset_pes.head()

,name,shirt_number,team_name,league,nationality,region,height,weight,age,foot,...,com_playing_style_incisive_run,com_playing_style_early_cross,com_playing_style_long_ball_expert,com_playing_style_long_ranger,height_over_185,age_u_24,age_25_29,age_30_plus,ball_color,rating_stars
0,NEYMAR,10,PSG,Ligue 1 Conforama,BRAZIL,South America,175,68,27,Right foot,...,1,0,0,0,0,0,1,0,black,5
1,M. NEUER,1,FC BAYERN MÜNCHEN,Other European Leagues,GERMANY,Europe,193,92,33,Right foot,...,0,0,0,0,1,0,0,1,black,5
2,EDU CAMPABADAL,22,LUGO RB,Spanish 2nd Division,SPAIN,Europe,178,77,26,Right foot,...,0,0,0,0,0,0,1,0,white,1
3,FRAN CRUZ,5,EXTREMADURA AR,Spanish 2nd Division,SPAIN,Europe,184,73,28,Right foot,...,0,0,0,0,0,0,1,0,white,1
4,DANI PINILLOS,23,BARNSLEY R,English 2nd Division,SPAIN,Europe,183,74,27,Left foot,...,0,1,1,0,0,0,1,0,white,1

In [3]:
dataset_pes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15035 entries, 0 to 15034
Columns: 124 entries, name to rating_stars
dtypes: float64(4), int64(109), object(11)
memory usage: 14.2+ MB

#### DATA SPLIT
Metode evaluasi model ini membagi dataset menjadi dua bagian untuk training data dan untuk testing data dengan proporsi tertentu.

##### Bagi dataset menjadi training set dan testing set dengan proporsi 70:30

In [4]:
data = dataset_pes[['height','weight','age','rating_stars']]
label = dataset_pes['team_name']

data_train, data_test, label_train, label_test = train_test_split(data, label, test_size=.3)

In [5]:
print(f'panjang data training {len(data_train)}',
     f'panjang label training {len(label_train)}',
     f'panjang data testing {len(data_test)}',
     f'panjang label testing {len(label_test)}',
     sep='\n')

panjang data training 10524
panjang label training 10524
panjang data testing 4511
panjang label testing 4511

#### DATA TRANSFORMASI
merubah skala data kedalam bentuk lain. Teknik penskalaan yang biasa dipakai yaitu normalisasi dan standardisasi

##### Lakukan normalisasi data pada salah satu attribute menggunakan Min Max scaler (buatlah copy dataset terlebih dahulu)

In [7]:
#Normalisasi
dataset_pes_copy = dataset_pes.copy()

scaler = MinMaxScaler()

normalize_dataset = scaler.fit_transform(dataset_pes_copy[['height', 'weight', 'age']])

normalize_dataset = pd.DataFrame(normalize_dataset)
normalize_dataset.rename(columns={ 0 :'height', 1 : 'weight', 2 : 'age'}, inplace=True)

normalize_dataset.head(5)

     height    weight       age
0  0.457627  0.338235  0.428571
1  0.762712  0.691176  0.642857
2  0.508475  0.470588  0.392857
3  0.610169  0.411765  0.464286
4  0.593220  0.426471  0.428571

##### Lakukan standarisasi pada dataset (buatlah copy dataset terlebih dahulu)

In [8]:
#Standarisasi
dataset_pes_copy.drop('team_name', axis=1, inplace=True)

standart_std = StandardScaler()

scaled_data = standart_std.fit_transform(dataset_pes_copy[['height', 'weight', 'age']])
scaled_data = pd.DataFrame(scaled_data)
scaled_data.rename(columns={ 0 :'height', 1 : 'weight', 2 : 'age'}, inplace=True)

scaled_data_pes = standart_std.fit_transform(dataset_pes[['height', 'weight', 'age']])
scaled_data_pes = pd.DataFrame(scaled_data_pes)
scaled_data_pes.rename(columns={ 0 :'height', 1 : 'weight', 2 : 'age'}, inplace=True)

print('Dataset sebelum scalling:',  # SEBELUM
      dataset_pes.drop('team_name', axis=1).head(6),'\n'
      f'Nilai standar deviasi:\n{np.std(scaled_data_pes)}',
      sep='\n', end='\n\n')

print('Dataset setelah scalling:',  # SESUDAH
      scaled_data[:6],
      f'Nilai standar deviasi: {np.std(scaled_data)}',
      sep='\n')

Dataset sebelum scalling:
             name shirt_number                  league nationality  \
0          NEYMAR           10       Ligue 1 Conforama      BRAZIL
1        M. NEUER            1  Other European Leagues     GERMANY
2  EDU CAMPABADAL           22    Spanish 2nd Division       SPAIN
3       FRAN CRUZ            5    Spanish 2nd Division       SPAIN
4   DANI PINILLOS           23    English 2nd Division       SPAIN
5       N. OBIORA            4                Liga NOS     NIGERIA

          region  height  weight  age        foot condition  ...  \
0  South America     175      68   27  Right foot         C  ...
1         Europe     193      92   33  Right foot         C  ...
2         Europe     178      77   26  Right foot         C  ...
3         Europe     184      73   28  Right foot         C  ...
4         Europe     183      74   27   Left foot         C  ...
5         Africa     183      77   28   Left foot         C  ...

  com_playing_style_incisive_run  com_playing_style_early_cross  \
0                              1                              0
1                              0                              0
2                              0                              0
3                              0                              0
4                              0                              1
5                              0                              0

   com_playing_style_long_ball_expert  com_playing_style_long_ranger  \
0                                   0                              0
1                                   0                              0
2                                   0                              0
3                                   0                              0
4                                   1                              0
5                                   0                              0

   height_over_185  age_u_24  age_25_29  age_30_plus  ball_color  rating_stars
0                0         0          1            0       black             5
1                1         0          0            1       black             5
2                0         0          1            0       white             1
3                0         0          1            0       white             1
4                0         0          1            0       white             1
5                0         0          1            0       white             1

[6 rows x 123 columns]

Nilai standar deviasi:
height    1.0
weight    1.0
age       1.0
dtype: float64

Dataset setelah scalling:
     height    weight       age
0 -0.841047 -0.961119  0.364933
1  1.809586  2.568684  1.594045
2 -0.399275  0.362557  0.160080
3  0.484270 -0.225743  0.569785
4  0.337012 -0.078668  0.364933
5  0.337012  0.362557  0.569785
Nilai standar deviasi: height    1.0
weight    1.0
age       1.0
dtype: float64

#### DATA CLEANING
Data cleaning adalah memperbarui, membetulkan, dan membuat data menjadi lebih rapi.

##### Lakukan Data cleaning pada data dengan nilai null .Ganti nilai null sesuai ketentuan.( bilangan desimal : mean)

In [9]:
# mengecek nilai null
nulls = dataset_pes_copy.isnull().sum().to_frame()
for index, row in nulls.iterrows():
    print(index +" = ", row[0])

name =  0
shirt_number =  0
league =  0
nationality =  0
region =  0
height =  0
weight =  0
age =  0
foot =  0
condition =  0
registered_position =  0
LWF =  1767
SS =  1767
CF =  1767
RWF =  1767
LMF =  0
DMF =  0
CMF =  0
AMF =  0
RMF =  0
LB =  0
CB =  0
RB =  0
offensive_awareness =  0
ball_control =  0
dribbling =  0
tight_possession =  0
low_pass =  0
lofted_pass =  0
finishing =  0
heading =  0
place_kicking =  0
curl =  0
speed =  0
acceleration =  0
kicking_power =  0
jump =  0
physical_contact =  0
balance =  0
stamina =  0
defensive_awareness =  0
ball_winning =  0
aggression =  0
gk_awareness =  0
gk_catching =  0
gk_clearing =  0
gk_reflexes =  0
gk_reach =  0
weak_foot_usage =  0
weak_foot_accuracy =  0
form =  0
injury_resistance =  0
overall_rating =  0
rating_as_GK =  0
rating_as_CB =  0
rating_as_LB =  0
rating_as_RB =  0
rating_as_DMF =  0
rating_as_CMF =  0
rating_as_LMF =  0
rating_as_RMF =  0
rating_as_AMF =  0
rating_as_LWF =  0
rating_as_RWF =  0
rating_as_SS =  0
rating_as_CF =  0
playing_style =  0
skill_cross_over_turn =  0
skill_early_cross =  0
skill_first_time_shot =  0
skill_incisive_run =  0
skill_one_touch_pass =  0
skill_chip_shot_control =  0
skill_heel_trick =  0
skill_man_marking =  0
skill_interception =  0
skill_gk_penalty_saver =  0
skill_penalty_specialist =  0
skill_step_on_skill_control =  0
skill_rising_shots =  0
skill_marseille_turn =  0
skill_gk_high_punt =  0
skill_heading =  0
skill_dipping_shot =  0
skill_outside_curler =  0
skill_captaincy =  0
skill_gamesmanship =  0
skill_gk_low_punt =  0
skill_low_lofted_pass =  0
skill_through_passing =  0
skill_fighting_spirit =  0
skill_flip_flap =  0
skill_weighted_pass =  0
skill_pinpoint_crossing =  0
skill_sombrero =  0
skill_acrobatic_clear =  0
skill_cut_behind_turn =  0
skill_long_range_drive =  0
skill_scotch_move =  0
skill_acrobatic_finishing =  0
skill_double_touch =  0
skill_gk_long_throw =  0
skill_long_throw =  0
skill_scissors_feint =  0
skill_long_range_shooting =  0
skill_track_back =  0
skill_rabona =  0
skill_knuckle_shot =  0
skill_no_look_pass =  0
skill_super_sub =  0
com_playing_style_trickster =  0
com_playing_style_mazing_run =  0
com_playing_style_speeding_bullet =  0
com_playing_style_incisive_run =  0
com_playing_style_early_cross =  0
com_playing_style_long_ball_expert =  0
com_playing_style_long_ranger =  0
height_over_185 =  0
age_u_24 =  0
age_25_29 =  0
age_30_plus =  0
ball_color =  0
rating_stars =  0

In [10]:
# bikin alat
imputer_mean = SimpleImputer(strategy = 'mean')

In [11]:
#info
dataset_pes_copy.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15035 entries, 0 to 15034
Data columns (total 123 columns):
 #    Column                              Non-Null Count  Dtype
---   ------                              --------------  -----
 0    name                                15035 non-null  object
 1    shirt_number                        15035 non-null  object
 2    league                              15035 non-null  object
 3    nationality                         15035 non-null  object
 4    region                              15035 non-null  object
 5    height                              15035 non-null  int64
 6    weight                              15035 non-null  int64
 7    age                                 15035 non-null  int64
 8    foot                                15035 non-null  object
 9    condition                           15035 non-null  object
 10   registered_position                 15035 non-null  object
 11   LWF                                 13268 non-null  float64
 12   SS                                  13268 non-null  float64
 13   CF                                  13268 non-null  float64
 14   RWF                                 13268 non-null  float64
 15   LMF                                 15035 non-null  int64
 16   DMF                                 15035 non-null  int64
 17   CMF                                 15035 non-null  int64
 18   AMF                                 15035 non-null  int64
 19   RMF                                 15035 non-null  int64
 20   LB                                  15035 non-null  int64
 21   CB                                  15035 non-null  int64
 22   RB                                  15035 non-null  int64
 23   offensive_awareness                 15035 non-null  int64
 24   ball_control                        15035 non-null  int64
 25   dribbling                           15035 non-null  int64
 26   tight_possession                    15035 non-null  int64
 27   low_pass                            15035 non-null  int64
 28   lofted_pass                         15035 non-null  int64
 29   finishing                           15035 non-null  int64
 30   heading                             15035 non-null  int64
 31   place_kicking                       15035 non-null  int64
 32   curl                                15035 non-null  int64
 33   speed                               15035 non-null  int64
 34   acceleration                        15035 non-null  int64
 35   kicking_power                       15035 non-null  int64
 36   jump                                15035 non-null  int64
 37   physical_contact                    15035 non-null  int64
 38   balance                             15035 non-null  int64
 39   stamina                             15035 non-null  int64
 40   defensive_awareness                 15035 non-null  int64
 41   ball_winning                        15035 non-null  int64
 42   aggression                          15035 non-null  int64
 43   gk_awareness                        15035 non-null  int64
 44   gk_catching                         15035 non-null  int64
 45   gk_clearing                         15035 non-null  int64
 46   gk_reflexes                         15035 non-null  int64
 47   gk_reach                            15035 non-null  int64
 48   weak_foot_usage                     15035 non-null  int64
 49   weak_foot_accuracy                  15035 non-null  int64
 50   form                                15035 non-null  int64
 51   injury_resistance                   15035 non-null  int64
 52   overall_rating                      15035 non-null  int64
 53   rating_as_GK                        15035 non-null  int64
 54   rating_as_CB                        15035 non-null  int64
 55   rating_as_LB                        15035 non-null  int64
 56   rating_as_RB                        15035 non-null  int64
 57   rating_as_DMF                       15035 non-null  int64
 58   rating_as_CMF                       15035 non-null  int64
 59   rating_as_LMF                       15035 non-null  int64
 60   rating_as_RMF                       15035 non-null  int64
 61   rating_as_AMF                       15035 non-null  int64
 62   rating_as_LWF                       15035 non-null  int64
 63   rating_as_RWF                       15035 non-null  int64
 64   rating_as_SS                        15035 non-null  int64
 65   rating_as_CF                        15035 non-null  int64
 66   playing_style                       15035 non-null  object
 67   skill_cross_over_turn               15035 non-null  int64
 68   skill_early_cross                   15035 non-null  int64
 69   skill_first_time_shot               15035 non-null  int64
 70   skill_incisive_run                  15035 non-null  int64
 71   skill_one_touch_pass                15035 non-null  int64
 72   skill_chip_shot_control             15035 non-null  int64
 73   skill_heel_trick                    15035 non-null  int64
 74   skill_man_marking                   15035 non-null  int64
 75   skill_interception                  15035 non-null  int64
 76   skill_gk_penalty_saver              15035 non-null  int64
 77   skill_penalty_specialist            15035 non-null  int64
 78   skill_step_on_skill_control         15035 non-null  int64
 79   skill_rising_shots                  15035 non-null  int64
 80   skill_marseille_turn                15035 non-null  int64
 81   skill_gk_high_punt                  15035 non-null  int64
 82   skill_heading                       15035 non-null  int64
 83   skill_dipping_shot                  15035 non-null  int64
 84   skill_outside_curler                15035 non-null  int64
 85   skill_captaincy                     15035 non-null  int64
 86   skill_gamesmanship                  15035 non-null  int64
 87   skill_gk_low_punt                   15035 non-null  int64
 88   skill_low_lofted_pass               15035 non-null  int64
 89   skill_through_passing               15035 non-null  int64
 90   skill_fighting_spirit               15035 non-null  int64
 91   skill_flip_flap                     15035 non-null  int64
 92   skill_weighted_pass                 15035 non-null  int64
 93   skill_pinpoint_crossing             15035 non-null  int64
 94   skill_sombrero                      15035 non-null  int64
 95   skill_acrobatic_clear               15035 non-null  int64
 96   skill_cut_behind_turn               15035 non-null  int64
 97   skill_long_range_drive              15035 non-null  int64
 98   skill_scotch_move                   15035 non-null  int64
 99   skill_acrobatic_finishing           15035 non-null  int64
 100  skill_double_touch                  15035 non-null  int64
 101  skill_gk_long_throw                 15035 non-null  int64
 102  skill_long_throw                    15035 non-null  int64
 103  skill_scissors_feint                15035 non-null  int64
 104  skill_long_range_shooting           15035 non-null  int64
 105  skill_track_back                    15035 non-null  int64
 106  skill_rabona                        15035 non-null  int64
 107  skill_knuckle_shot                  15035 non-null  int64
 108  skill_no_look_pass                  15035 non-null  int64
 109  skill_super_sub                     15035 non-null  int64
 110  com_playing_style_trickster         15035 non-null  int64
 111  com_playing_style_mazing_run        15035 non-null  int64
 112  com_playing_style_speeding_bullet   15035 non-null  int64
 113  com_playing_style_incisive_run      15035 non-null  int64
 114  com_playing_style_early_cross       15035 non-null  int64
 115  com_playing_style_long_ball_expert  15035 non-null  int64
 116  com_playing_style_long_ranger       15035 non-null  int64
 117  height_over_185                     15035 non-null  int64
 118  age_u_24                            15035 non-null  int64
 119  age_25_29                           15035 non-null  int64
 120  age_30_plus                         15035 non-null  int64
 121  ball_color                          15035 non-null  object
 122  rating_stars                        15035 non-null  int64
dtypes: float64(4), int64(109), object(10)
memory usage: 14.1+ MB

In [12]:
#mean
dataset_pes_copy['LWF'] = imputer_mean.fit_transform(dataset_pes_copy[['LWF']])
dataset_pes_copy['SS'] = imputer_mean.fit_transform(dataset_pes_copy[['SS']])
dataset_pes_copy['CF'] = imputer_mean.fit_transform(dataset_pes_copy[['CF']])
dataset_pes_copy['RWF'] = imputer_mean.fit_transform(dataset_pes_copy[['RWF']])

In [14]:
#nilai null
nulls = dataset_pes_copy.isnull().sum().to_frame()
for index, row in nulls.iterrows():
    print(index +" = ", row[0])

name =  0
shirt_number =  0
league =  0
nationality =  0
region =  0
height =  0
weight =  0
age =  0
foot =  0
condition =  0
registered_position =  0
LWF =  0
SS =  0
CF =  0
RWF =  0
LMF =  0
DMF =  0
CMF =  0
AMF =  0
RMF =  0
LB =  0
CB =  0
RB =  0
offensive_awareness =  0
ball_control =  0
dribbling =  0
tight_possession =  0
low_pass =  0
lofted_pass =  0
finishing =  0
heading =  0
place_kicking =  0
curl =  0
speed =  0
acceleration =  0
kicking_power =  0
jump =  0
physical_contact =  0
balance =  0
stamina =  0
defensive_awareness =  0
ball_winning =  0
aggression =  0
gk_awareness =  0
gk_catching =  0
gk_clearing =  0
gk_reflexes =  0
gk_reach =  0
weak_foot_usage =  0
weak_foot_accuracy =  0
form =  0
injury_resistance =  0
overall_rating =  0
rating_as_GK =  0
rating_as_CB =  0
rating_as_LB =  0
rating_as_RB =  0
rating_as_DMF =  0
rating_as_CMF =  0
rating_as_LMF =  0
rating_as_RMF =  0
rating_as_AMF =  0
rating_as_LWF =  0
rating_as_RWF =  0
rating_as_SS =  0
rating_as_CF =  0
playing_style =  0
skill_cross_over_turn =  0
skill_early_cross =  0
skill_first_time_shot =  0
skill_incisive_run =  0
skill_one_touch_pass =  0
skill_chip_shot_control =  0
skill_heel_trick =  0
skill_man_marking =  0
skill_interception =  0
skill_gk_penalty_saver =  0
skill_penalty_specialist =  0
skill_step_on_skill_control =  0
skill_rising_shots =  0
skill_marseille_turn =  0
skill_gk_high_punt =  0
skill_heading =  0
skill_dipping_shot =  0
skill_outside_curler =  0
skill_captaincy =  0
skill_gamesmanship =  0
skill_gk_low_punt =  0
skill_low_lofted_pass =  0
skill_through_passing =  0
skill_fighting_spirit =  0
skill_flip_flap =  0
skill_weighted_pass =  0
skill_pinpoint_crossing =  0
skill_sombrero =  0
skill_acrobatic_clear =  0
skill_cut_behind_turn =  0
skill_long_range_drive =  0
skill_scotch_move =  0
skill_acrobatic_finishing =  0
skill_double_touch =  0
skill_gk_long_throw =  0
skill_long_throw =  0
skill_scissors_feint =  0
skill_long_range_shooting =  0
skill_track_back =  0
skill_rabona =  0
skill_knuckle_shot =  0
skill_no_look_pass =  0
skill_super_sub =  0
com_playing_style_trickster =  0
com_playing_style_mazing_run =  0
com_playing_style_speeding_bullet =  0
com_playing_style_incisive_run =  0
com_playing_style_early_cross =  0
com_playing_style_long_ball_expert =  0
com_playing_style_long_ranger =  0
height_over_185 =  0
age_u_24 =  0
age_25_29 =  0
age_30_plus =  0
ball_color =  0
rating_stars =  0

##### Lakukan Data cleaning pada data dengan nilai duplikat.

In [15]:
dataset_pes_copy.duplicated().sum()

4

In [16]:
dataset_pes_copy[dataset_pes_copy.duplicated()]

,name,shirt_number,league,nationality,region,height,weight,age,foot,condition,...,com_playing_style_incisive_run,com_playing_style_early_cross,com_playing_style_long_ball_expert,com_playing_style_long_ranger,height_over_185,age_u_24,age_25_29,age_30_plus,ball_color,rating_stars
620,S. MOREO,9,Italian 2nd Division,ITALY,Europe,190,75,26,Right foot,C,...,0,0,0,0,1,0,1,0,bronze,2
621,WEI SHIHAO,7,CFA Super League,CHINA,Asia-Oceania,178,65,24,Right foot,C,...,0,0,0,0,0,1,0,0,white,1
11557,M. NEUER,1,Other European Leagues,GERMANY,Europe,193,92,33,Right foot,C,...,0,0,0,0,1,0,0,1,black,5
12266,NEYMAR,10,Ligue 1 Conforama,BRAZIL,South America,175,68,27,Right foot,C,...,1,0,0,0,0,0,1,0,black,5

In [17]:
dataset_pes_copy.drop_duplicates(inplace=True)

dataset_pes_copy.duplicated().sum()

0

##### Ganti tipe data salah satu attribute angka

In [18]:
dataset_pes_copy['rating_stars'].head()

0    5
1    5
2    1
3    1
4    1
Name: rating_stars, dtype: int64

In [19]:
dataset_pes_copy['rating_stars'].astype('object').head()

0    5
1    5
2    1
3    1
4    1
Name: rating_stars, dtype: object

#### ENCODING
Encoding adalah teknik yang mengubah variabel kategorikal menjadi variabel numerik. Teknik encoding yang paling terkenal adalah Ordinal Encoding dan One-Hot Encoding

##### Lakukan one hot encoding pada dataset yang kalian miliki.

In [20]:
#copydataset
dataset_pes_copy2 = dataset_pes.copy()

In [21]:
# buat alat
encoder_oneHot = OneHotEncoder(sparse=False)

temp_dataset = encoder_oneHot.fit_transform(dataset_pes_copy2[['region']]).astype('int32')

In [22]:
# format dataset ke dataframe
temp_dataset = pd.DataFrame(temp_dataset)

In [23]:
# hapus label sebelumnya attribute
dataset_pes_copy2.drop('region', axis=1, inplace=True)

In [24]:
# tambahkan label baru attribute
dataset_pes_copy2 = dataset_pes_copy2.join(temp_dataset)

In [25]:
# ganti nama label attribute 
dataset_pes_copy2.rename(columns = {0:'Africa', 1:'Asia-Oceania', 2:'Europe', 3 : 'North & Central America', 4 : 'South America'}, inplace=True)

In [26]:
# show the dataset record
dataset_pes_copy2.head(10)

,name,shirt_number,team_name,league,nationality,height,weight,age,foot,condition,...,age_u_24,age_25_29,age_30_plus,ball_color,rating_stars,Africa,Asia-Oceania,Europe,North & Central America,South America
0,NEYMAR,10,PSG,Ligue 1 Conforama,BRAZIL,175,68,27,Right foot,C,...,0,1,0,black,5,0,0,0,0,1
1,M. NEUER,1,FC BAYERN MÜNCHEN,Other European Leagues,GERMANY,193,92,33,Right foot,C,...,0,0,1,black,5,0,0,1,0,0
2,EDU CAMPABADAL,22,LUGO RB,Spanish 2nd Division,SPAIN,178,77,26,Right foot,C,...,0,1,0,white,1,0,0,1,0,0
3,FRAN CRUZ,5,EXTREMADURA AR,Spanish 2nd Division,SPAIN,184,73,28,Right foot,C,...,0,1,0,white,1,0,0,1,0,0
4,DANI PINILLOS,23,BARNSLEY R,English 2nd Division,SPAIN,183,74,27,Left foot,C,...,0,1,0,white,1,0,0,1,0,0
5,N. OBIORA,4,BOAVISTA,Liga NOS,NIGERIA,183,77,28,Left foot,C,...,0,1,0,white,1,1,0,0,0,0
6,JUAN CARLOS,1,GIRONA R,Spanish 2nd Division,SPAIN,186,85,31,Right foot,C,...,0,0,1,bronze,2,0,0,1,0,0
7,BERNARDO CRUZ,16,NUMANCIA R,Spanish 2nd Division,SPAIN,190,83,26,Right foot,C,...,0,1,0,white,1,0,0,1,0,0
8,RENÉ,25,PONFERRADA AB,Spanish 2nd Division,SPAIN,183,79,36,Right foot,C,...,0,0,1,bronze,2,0,0,1,0,0
9,R. KITOKO,23,SANTANDER VB,Spanish 2nd Division,CONGO DR,177,71,31,Right foot,C,...,0,0,1,white,1,1,0,0,0,0